version: '3'

services:
  web:
    image: nginx:1.15
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - .:/var/www/html:ro
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
    networks:
      - front
      - back

  php:
    build: infrastructure/docker/php
    user: www-data
    volumes:
      - .:/var/www/html
      - ./infrastructure/php/php.ini:/usr/local/etc/php/php.ini
      - ./infrastructure/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./infrastructure/php/ext-xdebug.ini:/usr/local/etc/php/conf.d/ext-xdebug.ini
    networks:
      - back

  mysql:
    image: mysql:5.7
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    networks:
      - back


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
    networks:
      - back


  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - API_URL=http://localhost/api/swagger.json
    networks:
      - front
      - back

volumes:
  database:
    driver: local


networks:
  front:
    driver: bridge
  back:
    driver: bridge